name: bcoom
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  cached_network_svg_image: ^1.2.0
  dartz: ^0.10.1
  dio: ^5.7.0
  dotted_border: ^3.1.0
  dotted_line: ^3.2.3
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.1.0
  flutter_html: ^3.0.0
  flutter_html_table: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.3
  flutter_svg_provider: ^1.0.7
  form_builder_validators: ^11.2.0
  get: ^4.7.3
  get_storage: ^2.1.1
  google_fonts: ^6.3.2
  image_picker: ^1.2.1
  injectable: ^2.7.1+2
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  logger: ^2.6.2
  material_symbols_icons: ^4.2874.0
  pinput: ^6.0.1
  shared_preferences: ^2.3.3
  simple_gradient_text: ^1.3.0
  url_launcher: ^6.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_flavorizr: ^2.4.1
  build_runner: ^2.10.4
  flutter_gen_runner: ^5.12.0


flutter_gen:
  output: lib/generated/
  line_length: 1000
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/splash/
    - assets/svgs/onboarding/
    - assets/svgs/icons/
    - assets/svgs/shapes/
    - assets/svgs/home/
    - assets/svgs/

    - assets/images/products/
    - assets/images/categories/


    - assets/logos/

    - assets/icons/